deploy fails if tests are not passing

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+## run tests, don't deploy if they fail
+./test
+if [ $? -ne 0 ]; then
+    exit $?
+fi
+
 APP_DIR=`mktemp -d -t /tmp`
 export POOTPOOT_ANALYTICS_KEY='UA-2604035-2'
 ./mkapp poot-poot $APP_DIR
